spring:
  application:
    name: gulimall-search

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719

  thymeleaf:
    cache: false

  redis:
    host: 192.168.88.131
    port: 6379

  session:
    store-type: redis

server:
  port: 12000

feign:
  sentinel:
    enabled: true
